name: Deploy Staging

on: 
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Cache composer dependencies
      uses: actions/cache@v1
      with:
        path: vendor
        key: composer-${{ hashFiles('composer.lock') }}

    - name: Create environment file
      uses: 1arp/create-a-file-action@0.2
      with:
        file: '.env'
        content: ${{ secrets.STAGING_ENV }}

    - name: Install dependencies
      run: |
        php --version
        composer install -n --prefer-dist
        
    - name: Deploy artifact
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        rm: false
        source: "app/, bootstrap/, config/, database/, public/, features/, resources/, routes/, storage/, tests/, vendor/, .env, artisan, composer.json"
        target: "${{ secrets.STAGING_PATH }}"

    - name: Configure app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ${{ secrets.STAGING_PATH }}
          chmod -R 777 storage
          php artisan migrate
          php artisan config:clear
          php artisan route:clear